title: UH GameLink
description: A way to connect gamers in the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/uh-gamelink/uh-gamelink.github.io
gems:
  - jekyll-mentions
